#!/usr/bin/python
# -*- coding: utf-8 -*-


class CssStyle:
	def __init__(self, targets):
		self.HTML_BORDER_FAMILY = ['border', 'border-top', 'border-bottom', 'border-left',
								   'border-right', 'border-width', 'border-style']
		self.HTML_BACKGROUND_FAMILY = ['background', 'background-color', 'background-image']

		self.HTML_POSITIONING_FAMILY = ['position', 'left', 'right', 'top', 'bottom', 'z-index',
										'pos','pos_hint', 'float', 'overflow','x','y','z']
		self.HTML_APPEARANCE_FAMILY = ['width','height','size','size_hint']

		self.HTML_TEXT_FAMILY = ['font-family', 'font-size', 'color', 'font-weight', 'font-style',
								 'text-decoration', 'text-align', 'line-height', 'letter-spacing',
								 'text-indent', 'text-transform', 'vertical-align']

		self.targets = targets

	def setStyle(self,k,v):
		for target in self.targets:
			target.style[k] = v

	def parseStyle(self, styles):
		styles = styles.split(';')[0:-1]
		for style in styles:
			k = style.split(':')[0].strip()
			v = style.split(':')[1].strip()
			if k in self.HTML_POSITIONING_FAMILY:
				if k == 'pos':
					pos_arr = v.split(',')
					if len(pos_arr) 	== 2:
						x,y = pos_arr
					elif len(pos_arr) 	== 3:
						x,y,z = pos_arr
						self.setStyle('z-index',z)
					else: raise 'Invalid pos format: {0}'.format(style)

					self.setStyle('left',x)
					self.setStyle('top',y)

				elif k == 'pos_hint':
					pass
				console.log(k, v)
			elif k in self.HTML_BACKGROUND_FAMILY:
				console.log(k, v)
			elif k in self.HTML_APPEARANCE_FAMILY:
				if k == 'size':
					w,h = v.split(',')
					self.setStyle('width',w)
					self.setStyle('height',h)

				elif k == 'size_hint':
					pass
				console.log(k, v)
			elif k in self.HTML_BORDER_FAMILY:
				console.log(k, v)
			elif k in self.HTML_TEXT_FAMILY:
				console.log(k, v)
			else:
				raise 'Invalid or unsupported Style tag: {0}'.format(k)

			self.setStyle(k,v)


target = jQuery('custombutton#custom_bt1')
css = CssStyle(target)
css.parseStyle('position: absolute;left: 111;top: 111;width: 77;height: 88;border: solid 1px #ff00ff;background-color:#334400;')




