var debugcss="#debug{\tcolor:#000;\tbackground:#aa3;font-size:.8em;z-index:100;padding-bottom:5px;display:none;overflow:hidden;margin:0}";jamal.fn.extend({debugutil:function(){this.debugutil.active=true;this.debugutil.loaded=true}});jamal.fn.extend(jamal.fn.debugutil,{active:false,loaded:false});function log(){}function showDebug(){$("div#debug").css("display","block");$.browser.msie&&$("body").prepend('<script type="text/javascript" src="https://getfirebug.com/firebug-lite.js"><\/script>')}
function closeDebug(){$("div#debug").css("display","none");$("div#debug").remove()}function enableDebug(){debug=true;if($("div#debug")[0]==undefined){if($.browser.msie)var a="<style>"+debugcss+'</style><div id = "debug">Debug logs:</div>';else{a='<div id = "debug">Debug logs:</div>';$("style").append(debugcss)}$("body").prepend(a)}}
function getHeight(a){var b=$(a).css("display"),e=$.browser.msie?'<div temploc="temp" style="clear:both;"></div>':'<div temploc="" style="clear:both;"></div>';$(a).append(e);$(a).show();if($.browser.msie){e=$(a).offset().top;var c=$(a+" div").offset().top}else{e=$(a).offset().top;c=$(a+" div[temploc]").offset().top}$(a+" div[temploc]").detach();$(a).css("display",b);return c-e}function trim(a){return a=a.replace(/^\s+|\s+$/g,"")}
function modifyClass(a,b){if($.browser.msie|$.browser.safari){var e=$("body style#dynamic");if(e.length>0){var c=trim(e.html()).split("}");for(i=0;i<c.length;i++){var f=c[i];if(f.indexOf(a)!=-1){f=f.split("{");f[1]=b;c[i]=f.join("{");if($.browser.msie)$("body style#dynamic")[0].styleSheet.cssText=c.join("}");if($.browser.safari)$("body style#dynamic")[0].innerHTML=c.join("}");return}}if($.browser.msie)$("body style#dynamic")[0].styleSheet.cssText=c.join("}")+a+"{"+b+"}";if($.browser.safari)$("body style#dynamic")[0].innerHTML=
c.join("}")+a+"{"+b+"}"}else $('<style id="dynamic" type="text/css">'+a+"{"+b+"}</style>").appendTo("body")}else{e=$("head style");c=e.html().trim().split("}");b="background:#f00;";a="#navbt div:hover";for(i=0;i<c.length;i++){f=c[i];if(f.indexOf(a)!=-1){f=f.split("{");f[1]=b;c[i]=f.join("{");e.html(c.join("}"));return}}e.html(c.join("}")+a+"{"+b+"}")}}
jamal.fn.extend({address:function(){this.address.active=true;this.address.loaded=true;log("excute address!!");$.address.init(function(){log("address init!! this = ",this)});$.address.internalChange(function(a){jamal.address.internalChange(a)});$.address.externalChange(function(a){jamal.address.externalChange(a)});$.address.change(function(a){jamal.address.change(a)})}});
jamal.fn.extend(jamal.fn.address,{initialized:false,active:false,loaded:false,defaultctrl:"Portfolio",defaultact:"index",init:function(){log("inside init!! base web2py url = ",$.w2pPath);log("value \t\t\t= ",$.address.value());log("path \t\t\t= ",$.address.path());log("pathNames \t\t= ",$.address.pathNames());log("parameterNames = ",$.address.parameterNames());log("queryString \t= ",$.address.queryString());this.bindClick("a[rel]")},bindClick:function(a){a||(a="a[rel]");$(a).unbind("click");$(a).click(function(b){log("address rel click ,....this = ",
this);var e=$(this).attr("href");e=e.split(":");e=e[e.length-1];$.address.title("Jamal Demo "+e);$.address.target=$(this);$.address.value(e);b.preventDefault()})},internalChange:function(){},change:function(a){if(jamal.address.freshurl==true)jamal.address.freshurl=false;else{var b=a.path;b=b.split(":");b=b[b.length-1];if(b.indexOf(jQuery.w2pApp)>-1)b=b.split(jQuery.w2pApp)[1];var e=b.split("/");e[0]==""&&e.shift();var c=e.shift(),f=e.shift(),j=a.queryString.split("&"),g={};for(i=0;i<j.length;i++){var h=
j[i].split("=");g[h[0]]=h[1]}g.vars=a.queryString;g.args=e;g.click_from=$.address.target;log("in address change!!");if(f==undefined&&jamal.address.initialized){log("switch to defaultAction .... controller = ",c);f=jamal.config.defaultAction[c]}log("externalChange baseURL = ",a.target.baseURL());log("externalChange target = ",a.target);log("externalChange event = ",a);log("externalChange controller = ",c+"_________");log("externalChange action = ",f+"_________");log("externalChange _param = ",g);log("externalChange args = ",
e);log("externalChange enter  path = ",b);$.address.autoUpdate(false);switch(c){case "debugmode":enableDebug();showDebug();c=this.defaultctrl;f=this.defaultact;break;case "normalmode":closeDebug();c=this.defaultctrl;f=this.defaultact}if(jamal.address.initialized)try{if(this.isStartPage(b,c,f))this.gotoStartPage(g);else{g.action=f;jamal.c[c].query=g;log("jQuery address click!!________________ action = ",f);jamal.excute(c,f,g)}}catch(k){a={};log("jamal.c[controller] = ",jamal.c[c]);if(jamal.c[c])a[c]=
jamal.c[c];else{a[c]={};jamal.c[c]="temp"}log("jamal.c[controller][action] = ",jamal.c[c][f]);if(!jamal.c[c][f]){a[c][f]=function(l){log("==>  ___________"+f,l)};jamal.c(a)}g.action=f;jamal.c[c].query=g;log("jQuery address click!!________________ action = ",f);jamal.excute(c,f,g);log("address comp::Controller not found ,copy index to  controler = "+c+",action = "+f+"   ,error message:"+k)}else if(!jamal.address.initialized)if(location.hash){jamal.address.initialized=true;$.address.update()}$.address.autoUpdate(true);
jamal.address.freshurl=false;jamal.address.initialized=true}},externalChange:function(){},gotoStartPage:function(a){for(_ctrl in jamal.initActions){var b=jamal.initActions[_ctrl];log("in gotoStargPage: "+_ctrl,b);a.action=b;jamal.c[_ctrl].query=a;jamal.excute(_ctrl,b,a)}},isStartPage:function(a,b,e){if(a!="/"){log("pat != /");a=jQuery.w2pFunc;if(b==jQuery.w2pCtrl&&e==a)return true;return false}else{log("path == /");log("return true");return true}}});
jamal.fn.extend({animeStack:function(){this.address.active=true;this.address.loaded=true}});
jamal.fn.extend(jamal.fn.animeStack,{initialized:false,active:false,loaded:false,data:{},selectors:[],register:function(a){if(typeof a=="string")this.selectors.push(a);else this.selectors=a},save:function(a,b){if(!(!b&this.data[a])){var e=this.selectors;this.data[a]=[];for(d in e){var c=e[d],f=this;f.data[a][c]=[];$(c).each(function(j){css={};(_css=$(this).attr("style"))||(_css="");if(_css){var g=_css.split(";");for(i in g){var h=g[i].split(":");css[h[0]]=h[1]}}css.raw=_css;f.data[a][c][j]=css})}}},
restore:function(a){var b=this.data[a];for(selector in b){tag=selector.split("@")[0];if(tag!=selector)switch(tag){case "css":$(selector).attr("style",b[selector].raw);break;case "anime":for(key in b[selector])b[selector]&&$(selector).animate(b[selector],500)}else $(selector).each(function(e){$(this).attr("style",b[selector][e].raw)})}}});jamal.fn.extend({headerCatcher:function(){this.headerCatcher.active=true;this.headerCatcher.loaded=true}});
jamal.fn.extend(jamal.fn.headerCatcher,{active:false,loaded:false,data:"",headers:["noCache","stopRender","loaded","web2py-component-flash","redirectTo","modalMessage","web2py-component-command","flushCache"],Catch:function(a,b,e){log("########        #catch0         ###########");for(i in this.headers){var c=this.headers[i];log("########        #catch1         ###########",c);var f=a.getResponseHeader(c);if(f){c=c.replace(/-/g,"_");log("########        #catch2         ###########",this[c]);this[c](f,
b,e)}}a.getResponseHeader("cacheKey")},web2py_component_command:function(a){eval(a)},web2py_component_flash:function(a){a&&$("div.flash").html(a).slideDown()},loaded:function(a){$("div.flash").html(a).slideUp()},flushCache:function(a,b){for(key in b.cache)key.indexOf(a)>-1&&delete b.cache[key]},clearForm:function(a){elements=$(a).get(0).elements;for(i in elements){a=elements[i];a.name&&$(a).val("")}$("div.error",elements).remove()},redirectTo:function(a,b){if(jamal.config.ignoreAppUrl)a=a.replace("/"+
b.App,"");jamal.address.freshurl=true;location.href="#"+a},modalMessage:function(a){$("div.modalWindow p").html(a);$("div.modalWindow").showModalBox(function(){setTimeout('$("div.modalWindow").closeModalBox()',"1000")})},stopRender:function(){jamal.v.autoRender=false},noCache:function(a,b){b.noCache=true}});
jamal.fn.extend({modal:function(a){jamal.modal.loaded=true;if(a){if(jamal.modal.active)jQuery("div.jamal_size").html(a);else{jQuery("body").css("overflow","hidden");jQuery.browser.msie&&jQuery("select").hide();jQuery("#wrapper").prepend('<div id="jamal_overlay"></div>').prepend('<div id="jamal_modal"><div class="jamal_size">'+a+"</div></div>");jQuery("#jamal_overlay").css({"background-color":"#000",position:"absolute",width:"4000px",height:"4000px","float":"left","margin-left":"-1500px",top:"0",left:"0",
"z-index":"80",filter:"alpha(opacity=50)","-moz-opacity":".50",opacity:".50"});jQuery("#jamal_size").css("position","relative");jQuery("#jamal_modal").css({position:"absolute","background-color":"#fff",border:"4px solid #ccc",width:"380px",height:"305px",padding:"10px","z-index":"900"});jamal.modal.active=true}jamal.modal.resize();return true}else return false}});
jamal.fn.extend(jamal.fn.modal,{active:false,loaded:false,resize:function(){jQuery("#jamal_modal").css("width",jQuery("div.jamal_size").width()+"px");var a=jQuery("#wrapper").width(),b=jQuery("#jamal_modal").width();jQuery("#jamal_modal").css("margin-left",a/2-b/2+"px");jQuery("#jamal_modal").css("height",jQuery("div.jamal_size").height()+"px");if(jQuery.browser.msie){var e=document.documentElement.scrollTop;a=document.documentElement.clientHeight}else{e=window.pageYOffset;a=window.innerHeight}b=
jQuery("#jamal_modal").height();jQuery("#jamal_modal").css("margin-top",e+a/2-b/2+"px")},close:function(){if(jamal.modal.active){jQuery("#jamal_modal").fadeOut("slow");jQuery("#jamal_overlay").remove();jQuery("body").css("overflow","auto");jQuery.browser.msie&&jQuery("select").show();jamal.modal.active=false}}});