jamal.extend(jamal.fn.v.prototype,{});
jamal.extend(jamal.fn.m.prototype,{property:{},db:"server",cacheQuery:"",url:"",jsonData:{},findAll:function(a){this.property={};if(this.get(this.getUrl(),a)=="fromCache")return this.cacheQuery[this.getUrl()]},findById:function(a,e){this.property={id:a};if(this.get(this.getUrl(),e)=="fromCache")return this.cacheQuery[this.getUrl()]},find:function(a,e){this.property=a;if(this.get(this.getUrl(),e)=="fromCache")return this.cacheQuery[this.getUrl()]},findInJson:function(a){var e=[];for(i=0;i<this.jsonData.__count__;){var c=
this.jsonData[i],g=false;for(q in a)if(c[q]!=a[q])g=true;g==false&&e.push(c)}return e},beforeFind:function(){}});
jamal.extend(jamal.fn.c.prototype,{components:["debugutil","address","headerCatcher","animeStack"],setCurrentPositionTo:function(a){log("@ @ @ @ @ @ -------  setCurrentPositionTo --------- @ @ @ @ @ @ type = ",a);try{if(jamal.c.portfolio.__show.animating)return}catch(e){jamal.c.portfolio.__show={animating:true}}var c=["div#website","div#blog","div#about","div#contact","div#portfolio"];a!="portfolio"|a!="blog"&&jamal.v.portfolio._menuSize("Tiny");var g="rgba(0,0,0,0)";if($.browser.msie){$("div#menu>div").css("width",
"auto");g="#00000000"}log("2 @ @ @ @ @ @ -------  setCurrentPositionTo --------- @ @ @ @ @ @ type = ",a);jamal.c.Nav.laststate=jamal.c.Nav.state;jamal.c.Nav._select(a);var b=jamal.c.Nav.laststate,d=jamal.c.Nav.state;registered=jamal.animeStack.selectors.length>0;saved=jamal.animeStack.data[b];log("3 @ @ @ @ @ @ -------  setCurrentPositionTo --------- @ @ @ @ @ @ type = ",a);registered||jamal.animeStack.register(["div#navigation","div#navigation div#img","div#navigation h5","div#navigation div#navbt",
"div#menu","div#menu #row1","div#menu #row2","div#menu>div>div>div","div#menu div.navBg","div#blogphoto","div#container","div#footer"]);b=="blog"&&jamal.animeStack.restore(b);if(d=="blog"){saved||jamal.animeStack.save(d);$.browser.safari&&$("div#navbt div").css("padding","16px 8px");$("div>div>div[style]",$("div#menu")).data("closeover",true)}else{if($.browser.safari){$("div#navbt div").css("padding","18px 8px");$("div#describe").css("margin-top","20px")}$.browser.mozilla&&$("div#describe").css("margin-top",
"20px");$("div>div>div[style]",$("div#menu")).data("closeover",false);$("div#login").css("display","none")}log("4 @ @ @ @ @ @ -------  setCurrentPositionTo --------- @ @ @ @ @ @ type = ",a);switch(a){case "portfolio":var h=4,f="";break;case "about":b=15;h=2;f=",div#corner";d={id:b,action:"inittitle",args:[b]};log("in setCurrentPositionTo....about","");jamal.v.portfolio._title({id:b,titleH:180,tableW:220,pW:110});jamal.excute("portfolio","inittitle",d);d=this.m.getColors();b={colors:d[b-1],imgnum:1};
jamal.v.portfolio._colorTransform(b);break;case "blog":b=16;h=1;f="";$("div#title").css("display","none");d=jamal.m.portfolio.getColors();b={colors:d[b-1],imgnum:1};jamal.v.portfolio._menuSize("Tiny2");jamal.v.portfolio._colorTransform(b);break;case "contact":b=14;h=3;f="";$("div#describe").html("");jamal.v.portfolio._title({id:b,titleH:90});d=this.m.getColors();b={colors:d[b-1],imgnum:1};jamal.v.portfolio._colorTransform(b);$("div#navigation").corner("Bottom 15px");$("div.logobg").corner("Bottom 15px");
$("div#navbt").corner("Bottom 15px");$("div#navbt li>a>div").corner("BR 15px");$("div#title").corner("Bottom 15px");break;case "website":b=17;h=0;f=",div#corner";$("div#describe").html("");jamal.v.portfolio._title({id:b,titleH:90});d=this.m.getColors();b={colors:d[b-1],imgnum:1};jamal.v.portfolio._colorTransform(b)}b=c.join(",");b=$(c+f);b.css({display:"none"});if(f==""){$("div#corner").css("display","block");$("div#corner").animate({width:750},500)}c=$(c[h]);if($.browser.msie){c.css("display","block");
jamal.c.portfolio.__show.animating=false}else{c.css({display:"block",opacity:0.1});c.animate({opacity:1},{queue:false,duration:500,complete:function(){jamal.c.portfolio.__show.animating=false}})}c=a=="portfolio"?400:$("div#"+a.toLowerCase()).innerHeight();log("5 @ @ @ @ @ @ -------  setCurrentPositionTo --------- @ @ @ @ @ @ type = ",a);if(a!="blog"){$("div#navigation").animate({width:750},500);$.browser.msie?$("div#title").animate({width:750},{queue:false,duration:500}):$("div#title").animate({width:750,
backgroundColor:g},{queue:false,duration:500});log("6 @ @ @ @ @ @ -------  setCurrentPositionTo --------- @ @ @ @ @ @ type = ",a);$("div#container").animate({height:c,width:750},{queue:false,duration:500,complete:function(){}})}},storeAnimeData:function(a){switch(a){case "blog":jamal.c.container=$("div#container").attr("style");jamal.c.nav_style=$("div#navigation").attr("style");jamal.c.nav_img_style=$("div#navigation div#img").attr("style");jamal.c.nav_h5_style=$("div#navigation h5").attr("style");
jamal.c.nav_bt_style=$("div#navigation div#navbt").attr("style")}},restoreAnimeData:function(){},beforeAction:function(a){switch(a.a){case "about":case "contact":case "website":this.c.setCurrentPositionTo(a.a);this.RenderAs("CustomRender")}},afterAction:function(){}});