var jamal=function(){if(window==this)return new jamal;return this.configure()};
jamal.fn=jamal.prototype={browser:"",version:"0.4",name:"",action:"",current:{},m:{},v:{},c:{},config:{},debug:false,events:{},initActions:{},start:function(){this.dir(jQuery.browser);this.debug===true&&$.browser.msie!=true&&window.console.time("Timing");var a=this.load();this.debug===true&&$.browser.msie!=true&&window.console.timeEnd("Timing");jQuery(window).error(function(b,c,d){var g;if(c&&d)g={name:"window.onerror",message:b,file:c,line:d,stack:""};jamal.fn===undefined?$j.error("Window error captured!",
g):jamal.fn.error("Window error captured!",g);return true});return a},log:function(a,b){if(this.debug===true&&$.browser.msie!=true){for(var c="",d=0;d<arguments.length;d++){c+=arguments[d];if(d!==arguments.length-1)c+=", "}try{console.log(a,b)}catch(g){}}},error:function(a){if(this.debug===true&&$.browser.msie!=true)if(arguments.length>1&&arguments[1]){e=arguments[1];window.console.error("Jamal Error: "+a,e);if(typeof e==="object"){typeof e.message==="object"&&this.dir(e.message);this.dir(e)}else this.dir(this.callstack())}else window.console.error("Jamal Error: "+
a)},callstack:function(){var a=/[(][^)]*[)]/,b=/(.*):(\d+)$/,c=Error().stack.split("\n");c.splice(0,2);for(var d in c){var g=c[d].split("@");if(g&&g.length==2){g[0].replace(a,"");g[1].match(b);g[1].match(b)}}},dir:function(a){this.debug===true&&$.browser.msie!=true&&window.console.dir(a)},configure:function(){try{var a=[],b={},c={};jQuery(".jamal").each(function(){thisdata=$(this).metadata();a.push(thisdata);var j=thisdata.controller,p=thisdata.action,l=thisdata.render;if(b[j]==undefined)b[j]={};
if(c[j]==undefined)c[j]={};if(l==undefined)l=true;c[j][p]=l;b[j][p]=$(this)})}catch(d){this.debug=true;this.error("jQuery Metadata Plugin failed to read the configuration. Probably there is no class=\"jamal {controller:'example',action:'index'}\" in your markup!",d)}this.config.controller={};for(i in a){var g=a[i],h=g.controller,n=g.action;g.filter={};var o=b[h][n];if(typeof g!=="object"){this.debug=true;this.error("No configuration found!");return false}else{this.name=h;if(this.config.controller[h]==
undefined){this.config.controller[h]=g;this.config.controller[h].render=c[h]}this.action[h]=n;for(key in g)if(key!="controller"&&key!="action"){this.config[key]=g[key];switch(key){case "debug":this.debug=g.debug}}log("controller = "+h,"action = "+n);this.config.controller[h].filter[n]=o;log(this.config.controller[h].filter.__count__)}}this.config.render=c;this.browser=$.browser.msie?"IE":"NotIE";return true},load:function(){var a=false;for(n in this.config.controller){var b=this.config.controller[n];
if(typeof this.c[n]!=="object"){jamal.fn=jamal;$j.c({Generic:{}});this.config.Generic={controller:"Generic",action:"index",debug:false}}try{this.current=this.c[b.controller]}catch(c){this.error("Controller error!",c)}if(this.current.components)for(var d in this.current.components)if(!this[this.current.components[d]].loaded)try{this[this.current.components[d]]()}catch(g){this.error(this.current.components[d]+" component error!",g)}if(typeof this.c[b.controller][b.action]==="function")try{this.current.filter=
b.filter;this.initActions[b.controller]=b.action;this.current.initAction=b.action;for(act in b.filter){this.current.action=act;var h={action:act},n=this.current.name,o=b.render[act];if(location.hash.indexOf(n)<0)if(o){log("in jamal: jamal.excute("+n+","+act+",_param)");jamal.excute(n,act,h)}}a=true}catch(j){this.error("Action couldn't be started!",j)}else this.error("Action not found!","there are some invalid definitions in your metadata ,or you must define actions where you defined in metadata")}return a},
noConflict:function(){if(jamal._$)$j=jamal._$j;return jamal},excute:function(a,b,c){if(typeof c!="object")c={action:b};log("excute "+a,b);log("excute query = ",c);var d=jamal.c[a];c.a=b;c.c=a;c.action=b;if(!d[b].parent){$.extend(d[b],d.actionBehavior);d[b].parent=d[b].c=d;d[b].action=b;d[b].name=a}try{d._beforeAction.call(d[b],c)!="STOP"&&d.beforeAction.call(d[b],c)!="STOP"&&d[b].call(d[b],c)!="STOP"&&d._afterAction.call(d[b],c)}catch(g){jamal.error(g)}},inflector:{singularize:function(a){return a.replace(/s$/,
"")},pluralize:function(a){return a+"s"}},_import:function(a){var b=a.split(".")[1],c=this.config.path;if(b!="css"){var d=document.getElementsByTagName("head")[0],g=document.createElement("script");g.type="text/javascript";if(b=="js"){g.src=a;d.appendChild(g)}else for(i in jamal.config.camelCase){b=jamal.config.camelCase[i];var h=a.split(b);if(h.length==2){h[0]=h[0].toLowerCase();b=b.toLowerCase();h[1]=h[0]+(b=="controller"?"_"+b:"")+".js";g.src=c[b]+h[1];d.appendChild(g);break}}}else document.write('<link href="'+
c.css+a+'" rel="stylesheet" type="text/css"></link>')}};jamal.extend=jamal.fn.extend=function(){var a=arguments[0],b=1;if(arguments.length==1){a=this;b=0}for(var c;(c=arguments[b++])!=null;)for(var d in c)a[d]=c[d];return a};jamal.m=jamal.fn.m=function(a){if(typeof a==="object"){var b,c;for(c in a){b=new jamal.fn.m(c);jamal.extend(b,a[c]);a[c]=b}jamal.extend(jamal.fn.m,a)}else{this.name=a;this.url="/"+this.name+"/getData"}};
jamal.fn.extend(jamal.fn.m.prototype,{db:"sever",cache:{},jsonData:{},url:"",property:{},settings:function(){var a=this,b=this.cache;return{type:"Get",dataType:"json",error:function(c,d,g){if(a.error()){jamal.error("Ajax - "+d+" ("+(c.status+" "+c.statusText)+")",g);b[this.url]=undefined}},success:function(c){jamal.ajaxSuccess(c);a.noError(c)&&this.callback&&this.callback(c)}}},getUrl:function(){var a="";for(prop in this.property){if(a=="")a="?";else a+="&";a+=prop+"="+this.property[prop]}return this.url+
a},isSet:function(a){for(v in a)if(!a[v])return false},isNotSet:function(a){return!this.isSet(a)},get:function(a,b){var c=this;if(this.cache[a]==undefined|this.cache[a]=="fetching"){if(this.cache[a]=="fetching")return false;var d=this.settings();d.url=a;d.beforeSend=function(g){jamal.ajaxSend(g);return c.beforeFind()};d.callback=function(g){g=c.afterFind(g);c.cache[a]=g;jQuery.extend(c.db,c.cache[a]);b&&b(param,g)};this.cache[a]="fetching";jQuery.ajax(d);return false}else return c.cache[a]},beforeFind:function(){},
afterFind:function(){},noError:function(a){if(a.error){a=a.error;$j.error(a.error+" ("+a.code+"): "+a.description+" in "+a.file);$j.log("Stack:");$j.log(a.stack);$j.log("Context:");$j.log(a.context);$j.log("Listing:");$j.dir(a.listing);return false}return true},url:""});
(function(){jamal.fn.ajaxSend=function(a){return typeof a==="function"?jQuery().bind("j_ajaxSend",a):jQuery.event.trigger("j_ajaxSend",[a])};jamal.fn.ajaxSuccess=function(a){return typeof a==="function"?jQuery().bind("j_ajaxSuccess",a):jQuery.event.trigger("j_ajaxSuccess",[a])}})();jamal.v=jamal.fn.v=function(a){if(typeof a==="object"){var b,c;for(c in a){b=new jamal.fn.v(c);jamal.extend(b,a[c]);a[c]=b}jamal.extend(jamal.fn.v,a)}else this.name=a};
jamal.fn.extend(jamal.fn.v.prototype,{template:{},renderTarget:{},behavior:{},renderParam:{},filter:{},App:"",Path:"",Ref:"",Host:"",noCache:false,cache:{},w2p_cache_stack:[],autoRender:true,_beforeRender:function(a,b){log("_beforeRender "+a,b);this.behavior[a]=b.renderBehavior.toLowerCase();var c=b.eq;if(this.behavior[a]=="default"){this.refreshFilter(a);if(c!=undefined){log(this.name+" "+a+" zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz 1 has eq",b.vars);this.setView(a,b)}else if(this.renderTarget[a])log(this.name+
" "+a+" zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz 3",b.vars);else{log(this.name+" "+a+" zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz 2",b.vars);this.setView(a)}log(this.name+" "+a+" _beforeRender ...........args = ",b.args);b.setURL||this.setTemplate(a,b.args,b.vars)}log("_beforeRender setting = ",b);log("template = ",this.template[a]);log("renderTarget = ",this.renderTarget[a]);this.beforeRender(a,b);this.renderBehavior(a,b)},beforeRender:function(){},behaviorList:{customrender:function(a,b){log(this.name+" "+
a+" customRender.....enter!! this = ",this);var c=b.renderParam;this[a]&&this[a](a,c);this._afterRender(a);this.afterRender(a,c)},"default":function(a,b){log(this.name+" "+a+"______________________defaultRender  view = "+a,this);var c=this.template[a],d=b.renderParam,g=this;m=b.type?"Post":"Get";if(jamal.config.ignoreAppUrl)c=c.replace("/"+this.App,"");log(this.name+" "+a+"______________________defaultRender  m = "+m,this.cache[c]!=undefined);log("tmpl = "+c,this.cache[c]);if(this.cache[c]&&m!="Post"){var h=
this.cache[c].cache,n=this.cache[c].header;log(this.name+" "+a+"^^^^^^^^^^^^^^^^^^F O U N D    CACHE!! ^^^^^^^^^^^^^^^^^^^^^^^^^^ tmpl = "+c);successCallback(h,"fromCache",n,c,m,a,this)}else{this.loading(a);log("tmpl = "+c,this.cache[c]);var o=c.split("?")[0];successCallback=function(j,p,l,s,t,q,k){log(k.name+" "+q+" sucess Callback tmpl = "+s,p);k.App=l.getResponseHeader("application");k.Path=l.getResponseHeader("path_info");k.Ref=l.getResponseHeader("http_referer");k.Ctrl=l.getResponseHeader("controller");
k.Func=l.getResponseHeader("function");if(jamal.address.isStartPage(k.Path,k.Ctrl,k.Func))location.href="#";else{jamal.headerCatcher.Catch(l,k,q);if(!k.noCache){log("in default________cache it ________",s);k.cache[s]={cache:j,header:l};k.w2p_cache_stack.push(s)}log(k.name+" "+q+" fetch template success ,begin to render!"+s);if(k.autoRender)if(k[q]){log(k.name+" "+q+" found action in view ,begin to render!",s);k[q](d,j,l)?k.render(q,s):log(k.name+" "+q+" rendering was blocked from view!",d)}else k.render(q,
s);k.autoRender=true;log(k.name+" "+q+" ^^^^^^^^ fetch template success ,current.afterRender(view)",s);k._afterRender(q,b);k.afterRender(q,d)}};log("send url = ",o);if($.browser.msie){log("send url = ",o);xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");log("send url = ",o);if(b.vars)o=o+"?"+b.vars;log("send url = ",o);xmlhttp.open(m,o,true);xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4){log("success send..... xhr = ",xmlhttp);log("success send..... headers = ",xmlhttp.getAllResponseHeaders());
var j=xmlhttp,p=j.responseText,l=j.getResponseHeader("redirectTo");l?successCallback(p,"",j,jamal.v.prototype.full_address(l),m,a,g):successCallback(p,"",j,o,m,a,g)}else log("ajax error!!***************xhr = ",xmlhttp)};xmlhttp.setRequestHeader("web2py-component-location",document.location);xmlhttp.setRequestHeader("web2py-component-element",g.filter[a].attr("id"));xmlhttp.setRequestHeader("jamal-cacheStack",g.w2p_cache_stack.pop());xmlhttp.send(null)}else{log("setting.vars , url: "+b.vars,c);$.ajax({url:o,
type:m,data:b.vars,view:a,current:this,cache:false,contentType:"text/html; charset=utf-8",beforeSend:function(j){log("beforeSend view = ",a);j.setRequestHeader("web2py-component-location",document.location);j.setRequestHeader("web2py-component-element",g.filter[a].attr("id"));j.setRequestHeader("jamal-cacheStack",g.w2p_cache_stack.pop())},success:function(j,p,l){log("xhr = ",l);r=l.getResponseHeader("redirectTo");log("success...... this.url = ",this.url);r?successCallback(j,p,l,jamal.v.prototype.full_address(r),
m,this.view,this.current):successCallback(j,p,l,this.url,m,this.view,this.current)},error:function(j,p,l){log("ajax error!!***************xhr = ",j);log("ajax error!!***************txt = ",p);log("ajax error!!***************err = ",l);jamal.error("template not found!: "+c)}})}}}},loading:function(){},_afterRender:function(a,b){log("_afterRender: ",a);var c=this.filter[a];if(c!=undefined){var d=jQuery("form",c);if(d.length>0){for(f in d);log(" W E B 2 P y  T R A P F O R M    teset  t - ",d);log("trap web2py form========== T R A P W 2 P F O R M ========= t.selector = ",
d.selector);log(" W E B 2 P y  T R A P F O R M    this.filter[view]",c);data=d.serialize();var g=c.attr("id");log("trap web2py form========== T R A P W 2 P F O R M ========= content = ",g);log("trap web2py form========== T R A P W 2 P F O R M ========= jQuery._w2pRef = ",this.Path.replace("/"+this.App,""));log("trap web2py form========== T R A P W 2 P F O R M ========= data = ",data);d=$("div.hidden>input[name=action]",d);d=d.length>0?d.attr("value"):"";if(!$("form",c).attr("trapped"))if(d){$("form",
c).attr("trapped",true);this.web2py_trap_form(a,d,g)}else{log("setting.formAct",b.formAct);url=b.formAct?this[a].formAct:jamal.v.prototype.full_address(this.Path);url=jamal.v.prototype.full_address(this.Path);$("form",c).attr("trapped",true);this.web2py_trap_form(a,url,g)}}this.web2py_ajax_init();jamal.address.init()}},web2py_ajax_init:function(){jQuery(".error").hide().slideDown("slow");jQuery(".flash").unbind("click");jQuery(".flash").click(function(){jQuery(this).fadeOut("slow");return false})},
renderBehavior:function(a,b){log("in view: renderBehavior: "+this.name+" ,"+a+" = ",this.behavior[a].toString());log("in view: renderBehavior: this.behaviorList = ",this.behaviorList[this.behavior[a]]);this.behaviorList[this.behavior[a]].call(this,a,b)},getActionProp:function(a){return jamal.c[this.name].getActionProp(a)},setActionProp:function(a,b){jamal.c[this.name].setActionProp(a,b)},refreshFilter:function(a){try{if(this.renderTarget[a].parent().length==0){this.renderTarget[a]=this.filter[a]=
"";return true}}catch(b){return true}return false},afterRender:function(){},full_address:function(a){if(a.indexOf(jQuery.w2pApp)>-1)var b=jQuery.w2pHost,c="";else{b=jQuery.w2pHost;c="/"+jQuery.w2pApp}if(a[0]!="/")if(a.substr(0,3)=="http")return a;else a="/"+a;return b+c+a},web2py_trap_form:function(a,b,c){log("trap test target = ",jQuery("#"+c+" form"));var d=this,g={renderParam:"",type:"Post"};jQuery("#"+c+" form").each(function(){var h=jQuery(this);log("trap test1 form  = ",h);h.hasClass("no_trap")||
h.submit(function(){jQuery(".flash").hide().html("");log("callfrom = ",d);if(b)d.template[a]=b;if(d["_"+a+"_formAct"])if(!d["_"+a+"_formAct"](h))return false;g.vars=h.serialize();d.behaviorList["default"].call(d,a,g);return false})})},URL:function(a){var b=this.App=jQuery.w2pApp;this.Path=jQuery.w2pPath;this.Ref=jQuery.w2pRef;var c=this.Host=jQuery.w2pHost;this.Ctrl=jQuery.w2pCtrl;var d=a.c,g=a.a,h=a.f,n=a.args;a=a.vars;log("in URL _____________________________ vars = ",a);g&&(b=g);b=(c+"/"+b+"/").split(d)[0];
h="/"+h;n=typeof n=="object"?n.length>0?"/"+n.join("/"):"":"";if(typeof a=="object")a=a.length>0?"?"+a.join("&"):"";else a?a="?"+a:a="";log("in URL _____________________________ = ",b+d+h+n+a);return b+d+h+n+a},setTarget:function(a,b){this.renderTarget[a]=b},setURL:function(a,b){this.template[a]=b},setTemplate:function(a,b,c){this.template[a]=this.URL({a:"",c:this.name,f:a,args:b,vars:c})},setView:function(a,b){var c=this.filter[a];log(this.name+" "+a+"_____in setView ,div[view]  = ",$("div[view]",
c));var d=this;if(b)var g=parseInt(b.eq);if(c){if(c.parent().length>0){log("============= target has already set before!",c);log("============= target has already set before!",c.parent().length);this.renderTarget[a]=c;return}this.filter[a]=this.renderTarget[a]=""}for(key in this.filter){c=this.filter[key];if(c.is("[view*="+a+"]")){c=c;var h=c.length;log("============= find view in metadata init",c);this.filter[a]=c;this.renderTarget[a]=c;return}else{c=$("div[view*="+a+"]",c);if(h=c.length){log("============= found matched");
if(h==1){d.filter[a]=c;d.renderTarget[a]=c;log("============= found view",c);return}else try{d.filter[a]=c.eq(g);d.renderTarget[a]=c.eq(g);log("============= found view and eq",d.filter[a]);return}catch(n){jamal.error('Cannot process_general_config multiple "view" without asigning "eq" queryString!',n);return}}}}log("============= use init as renderTarget");if(this.filter.length==0|!this.filter[a]){d=this;var o=this.name;$("div[ctrl]").each(function(){var j=$(this).attr("ctrl").split(",");for(i in j)if(j[i]==o){d.filter[a]=
$(this);d.renderTarget[a]=$(this);break}})}jamal.error("Cannot find view! in function of setView :",a)},addBehavior:function(a,b){this.behaviorList[a.toLowerCase()]=b},decode_html:function(a){if(typeof a==="string"){var b=document.createElement("div");b.innerHTML=a.replace(/<\/?[^>]+>/gi,"");return b.childNodes[0]?b.childNodes[0].nodeValue:""}else return""},render:function(a,b){var c=this.renderTarget[a];log("usage1 url = "+b,c);log(b,this.cache[b]);try{var d=this.cache[b].cache}catch(g){d=this.cache.temp.cache}c.html(d)}});
jamal.c=jamal.fn.c=function(a){if(typeof a==="object"){if(jamal.fn===undefined)jamal.fn=jamal;var b,c;for(c in a){b=new jamal.fn.c(c);jamal.extend(b,a[c]);var d=c.substr(0,c.length);b.m=jamal.fn.m[d]?jamal.fn.m[d]:jamal.fn.m[d]=new jamal.fn.m(d);b.v=jamal.fn.v[c]?jamal.fn.v[c]:jamal.fn.v[c]=new jamal.fn.v(c);a[c]=b}jamal.extend(jamal.fn.c,a)}else this.name=a};
jamal.fn.extend(jamal.fn.c.prototype,{filter:{},render:true,_index:"",renderview:"",query:{},action:"",_beforeAction:function(a){log("_beforeAction "+a.a,a);this.c.setActionProp(a.a,a);log("_beforeAction this.actionProp = ",this.actionProp)},getActionProp:function(a){return this[a].actionProp},setActionProp:function(a,b){var c=this[a].actionProp==undefined?{render:true,view:a,renderBehavior:"Default"}:this[a].actionProp;log("in setActionProp","");log(this[a].actionProp,b);$.extend(c,b);this[a].actionProp=
c;log(this[a].actionProp,b)},URL:function(a){return this.v.URL(a)},setURL:function(a,b){this.v.setURL(a,b)},actionBehavior:{action:"",parent:{},RenderView:function(a){this.parent.setActionProp(this.action,{render:true,view:a})},RenderAs:function(a,b){this.parent.setActionProp(this.action,{renderBehavior:a,renderParam:b})},CancelView:function(a){if(a==undefined)a=this.action;this.parent.setActionProp(a,{render:false,view:""});return"STOP"},formAct:function(a){this.parent.setActionProp(this.action,
{formAct:a})},setURL:function(a){this.parent.setActionProp(this.action,{setURL:true});this.parent.v.setURL(this.action,a)}},_afterAction:function(a){log("_afterAction query = ",a);log("_afterAction actionProp = ",this.actionProp);var b=this.actionProp.render;if(b){log("_afterAction = "+a.a+"    , isrender = "+b+"   this.c.name = "+this.c.name+",  this.c.filter = ",this.c.filter);a=this.actionProp.view;log("_afterAction ,jamal.v[this.c.name].filter = "+jamal.v[this.c.name].filter);jamal.v[this.c.name].filter=
this.c.filter;jamal.v[this.c.name]._beforeRender(a,this.actionProp);log("end of _afterAction","")}},redirectToAction:function(a,b){jamal.excute(this.name,a,b)},beforeAction:function(){},afterAction:function(){},init:function(a){jamal.current[jamal.action](a)}});